language: php

php:
  - 5.5
  - 5.6
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

before_install:
  - composer self-update

install:
  - composer install --prefer-source

before_script:
  # php linter
  - vendor/bin/parallel-lint -e php src tests
  # php copy/paste detector
  - vendor/bin/phpcpd src tests
  # php code sniffer
  - vendor/bin/phpcs src tests/ZenifyTests --standard=vendor/zenify/coding-standard/src/ZenifyCodingStandard/code-sniffer-ruleset.xml --ignore=bootstrap
  # php mess-detector
  - vendor/bin/phpmd src,tests text vendor/zenify/coding-standard/src/ZenifyCodingStandard/mess-detector-ruleset.xml

script:
  - vendor/bin/phpunit --coverage-clover=coverage.clover

after_script:
  # move code coverage
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
